### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by BryanDavis999** [BryanDavis999/wheel#7]

**Comment by BryanDavis999** [comment]
Hey @yedhink & @navaneethsdk 

I've completed all the other tasks but I've hit a bit of a snag in deployment. I've gotten locked out of my Heroku Account and can't seem to access it / reset password. I have no idea why but it's probably cause it's been a while since I've logged in.
I've submitted a support ticket and hopefully should get a response in 1-2 business days.

Will update once I manage to get my account back / figure out another way to deploy.

**Comment by navaneethsdk** [comment]
@BryanDavis999 Please proceed with the deployment using neetoDeploy. Refer: https://help.neetodeploy.com/

**Comment by navaneethsdk** [comment]
@BryanDavis999 a few comments:
- [ ] Why doesn't the Cancel button have a type reset? https://github.com/BryanDavis999/wheel/blob/7d1f25861732fcc06a6953a4bca315d852e4e000/app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx#L80
- [ ] Add `noValidate` tag here to disable [validation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attributes) from the HTML form element. https://github.com/BryanDavis999/wheel/blob/7d1f25861732fcc06a6953a4bca315d852e4e000/app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx#L36
- [ ] `Update` sounds more like a technical keyword. Let's use `Save changes` for updating notes as well. https://github.com/BryanDavis999/wheel/blob/7d1f25861732fcc06a6953a4bca315d852e4e000/app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx#L75
- [ ] Why is `translation` not used here? https://github.com/BryanDavis999/wheel/blob/7d1f25861732fcc06a6953a4bca315d852e4e000/app/javascript/src/components/Dashboard/Notes/Pane/Edit.jsx#L14
- [ ] What is the use of passing `refetch` as a prop if it's not being used in the `Form` component? https://github.com/BryanDavis999/wheel/blob/7d1f25861732fcc06a6953a4bca315d852e4e000/app/javascript/src/components/Dashboard/Notes/Pane/Edit.jsx#L17 https://github.com/BryanDavis999/wheel/blob/7d1f25861732fcc06a6953a4bca315d852e4e000/app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx#L16
- [ ] Please avoid unnecessary namespacing in `app/javascript/src/components/Dashboard/Notes/NotesList/Note`. Refer https://academy.bigbinary.com/learn-react/naming-conventions/avoiding-unnecessary-namespacing
- [ ] Let's remove this. I think it is unnecessary. https://github.com/BryanDavis999/wheel/blob/7d1f25861732fcc06a6953a4bca315d852e4e000/app/javascript/src/components/Dashboard/Notes/DeleteAlert.jsx#L20
- [ ] Let's not use abbreviations, its better to expand them as `event`. https://github.com/BryanDavis999/wheel/blob/7d1f25861732fcc06a6953a4bca315d852e4e000/app/javascript/src/components/Dashboard/Notes/index.jsx#L58
- [ ] Please make use of `classnames` here: https://github.com/BryanDavis999/wheel/blob/7d1f25861732fcc06a6953a4bca315d852e4e000/app/javascript/src/components/Dashboard/Contacts/Table/index.jsx#L26-L28

cc: @yedhink

**Comment by BryanDavis999** [comment]
Application has been deployed on NeetoDeploy instead.

The PR containing all the above changes is located at https://bryan-nuic-pr-17.neetoreviewapp.net
